name: Generate Snake

on:
  schedule:
    # Run the workflow every 6 hours
    - cron: "0 */6 * * *"
  push:
    # Run the workflow when there are new commits pushed to the repository
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate snake contribution graph
        run: python generate_snake.py ${{ secrets.GITHUB_TOKEN }}
